[[pages]]
path = "/"
screenshotTimestamp = "2026-05-21T03:28:12Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/768b5b83-a879-41f7-b33b-d007b1f69430/143200f5-fc30-4ced-a69d-e35c875595c2/8qUXGmc"

[[pages]]
path = "/edit-profile"
screenshotTimestamp = "2026-05-21T04:46:35Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/768b5b83-a879-41f7-b33b-d007b1f69430/143200f5-fc30-4ced-a69d-e35c875595c2/kCWGCfY"

[[pages]]
path = "/modes"
screenshotTimestamp = "2026-05-01T00:56:31Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/768b5b83-a879-41f7-b33b-d007b1f69430/ad47117a-3da5-4b54-9687-78e3838a7107/olaylrD"

[[pages]]
path = "/dashboard"
screenshotTimestamp = "2026-05-21T03:53:56Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/768b5b83-a879-41f7-b33b-d007b1f69430/143200f5-fc30-4ced-a69d-e35c875595c2/uAUw7gH"

[[pages]]
path = "/verification"
screenshotTimestamp = "2026-05-21T04:15:05Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/768b5b83-a879-41f7-b33b-d007b1f69430/143200f5-fc30-4ced-a69d-e35c875595c2/MdZTmTS"

[[pages]]
path = "/p/duecedinero"
screenshotTimestamp = "2026-05-21T04:42:45Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/768b5b83-a879-41f7-b33b-d007b1f69430/143200f5-fc30-4ced-a69d-e35c875595c2/NfXEMzD"

[[pages]]
path = "/admin"
screenshotTimestamp = "2026-05-21T05:00:56Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/768b5b83-a879-41f7-b33b-d007b1f69430/143200f5-fc30-4ced-a69d-e35c875595c2/YTsqiFs"
